// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Series
	Event
	Venue
	Location
	Track
	Activity
	Group
	Person
	Sponsor
	Sponsorship
	Vendor
	Vending
*/
package message

import proto "github.com/golang/protobuf/proto"
import google_protobuf "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Activity_Type int32

const (
	Activity_TALK   Activity_Type = 0
	Activity_CLASS  Activity_Type = 1
	Activity_SOCIAL Activity_Type = 2
	Activity_HACK   Activity_Type = 3
)

var Activity_Type_name = map[int32]string{
	0: "TALK",
	1: "CLASS",
	2: "SOCIAL",
	3: "HACK",
}
var Activity_Type_value = map[string]int32{
	"TALK":   0,
	"CLASS":  1,
	"SOCIAL": 2,
	"HACK":   3,
}

func (x Activity_Type) String() string {
	return proto.EnumName(Activity_Type_name, int32(x))
}

type Sponsorship_Level int32

const (
	Sponsorship_BRONZE   Sponsorship_Level = 0
	Sponsorship_SILVER   Sponsorship_Level = 1
	Sponsorship_GOLD     Sponsorship_Level = 2
	Sponsorship_PLATINUM Sponsorship_Level = 3
)

var Sponsorship_Level_name = map[int32]string{
	0: "BRONZE",
	1: "SILVER",
	2: "GOLD",
	3: "PLATINUM",
}
var Sponsorship_Level_value = map[string]int32{
	"BRONZE":   0,
	"SILVER":   1,
	"GOLD":     2,
	"PLATINUM": 3,
}

func (x Sponsorship_Level) String() string {
	return proto.EnumName(Sponsorship_Level_name, int32(x))
}

type Series struct {
	Id     int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Events []*Event `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
}

func (m *Series) Reset()         { *m = Series{} }
func (m *Series) String() string { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()    {}

func (m *Series) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Id         int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name       string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Begins     *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=begins" json:"begins,omitempty"`
	Ends       *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=ends" json:"ends,omitempty"`
	Activities []*Activity                `protobuf:"bytes,5,rep,name=activities" json:"activities,omitempty"`
	Tracks     []*Track                   `protobuf:"bytes,6,rep,name=tracks" json:"tracks,omitempty"`
	Organizers []*Person                  `protobuf:"bytes,7,rep,name=organizers" json:"organizers,omitempty"`
	Attendees  []*Person                  `protobuf:"bytes,8,rep,name=attendees" json:"attendees,omitempty"`
	Sponsors   []*Sponsorship             `protobuf:"bytes,9,rep,name=sponsors" json:"sponsors,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetBegins() *google_protobuf.Timestamp {
	if m != nil {
		return m.Begins
	}
	return nil
}

func (m *Event) GetEnds() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ends
	}
	return nil
}

func (m *Event) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *Event) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

func (m *Event) GetOrganizers() []*Person {
	if m != nil {
		return m.Organizers
	}
	return nil
}

func (m *Event) GetAttendees() []*Person {
	if m != nil {
		return m.Attendees
	}
	return nil
}

func (m *Event) GetSponsors() []*Sponsorship {
	if m != nil {
		return m.Sponsors
	}
	return nil
}

type Venue struct {
	Id          int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address     string      `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	PhoneNumber string      `protobuf:"bytes,4,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Email       string      `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Locations   []*Location `protobuf:"bytes,6,rep,name=locations" json:"locations,omitempty"`
	Events      []*Event    `protobuf:"bytes,7,rep,name=events" json:"events,omitempty"`
}

func (m *Venue) Reset()         { *m = Venue{} }
func (m *Venue) String() string { return proto.CompactTextString(m) }
func (*Venue) ProtoMessage()    {}

func (m *Venue) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *Venue) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Location struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Capacity int32  `protobuf:"varint,3,opt,name=capacity" json:"capacity,omitempty"`
	Address  string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Venue    *Venue `protobuf:"bytes,6,opt,name=venue" json:"venue,omitempty"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}

func (m *Location) GetVenue() *Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

type Track struct {
	Id         int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Event      *Event      `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	Activities []*Activity `protobuf:"bytes,4,rep,name=activities" json:"activities,omitempty"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}

func (m *Track) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Track) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

type Activity struct {
	Id         int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name       string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Event      *Event                     `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	Track      *Track                     `protobuf:"bytes,4,opt,name=track" json:"track,omitempty"`
	Begins     *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=begins" json:"begins,omitempty"`
	Ends       *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=ends" json:"ends,omitempty"`
	Location   *Location                  `protobuf:"bytes,7,opt,name=location" json:"location,omitempty"`
	Presenters []*Person                  `protobuf:"bytes,8,rep,name=presenters" json:"presenters,omitempty"`
	Attendees  []*Person                  `protobuf:"bytes,9,rep,name=attendees" json:"attendees,omitempty"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}

func (m *Activity) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Activity) GetTrack() *Track {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *Activity) GetBegins() *google_protobuf.Timestamp {
	if m != nil {
		return m.Begins
	}
	return nil
}

func (m *Activity) GetEnds() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ends
	}
	return nil
}

func (m *Activity) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Activity) GetPresenters() []*Person {
	if m != nil {
		return m.Presenters
	}
	return nil
}

func (m *Activity) GetAttendees() []*Person {
	if m != nil {
		return m.Attendees
	}
	return nil
}

type Group struct {
	Id             int64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Event          *Event    `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	Administrators []*Person `protobuf:"bytes,4,rep,name=administrators" json:"administrators,omitempty"`
	Members        []*Person `protobuf:"bytes,5,rep,name=members" json:"members,omitempty"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}

func (m *Group) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Group) GetAdministrators() []*Person {
	if m != nil {
		return m.Administrators
	}
	return nil
}

func (m *Group) GetMembers() []*Person {
	if m != nil {
		return m.Members
	}
	return nil
}

type Person struct {
	Id         int64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Fname      string      `protobuf:"bytes,2,opt,name=fname" json:"fname,omitempty"`
	Lname      string      `protobuf:"bytes,3,opt,name=lname" json:"lname,omitempty"`
	Email      string      `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Attending  []*Activity `protobuf:"bytes,5,rep,name=attending" json:"attending,omitempty"`
	SpeakingAt []*Activity `protobuf:"bytes,7,rep,name=speakingAt" json:"speakingAt,omitempty"`
	Groups     []*Group    `protobuf:"bytes,8,rep,name=groups" json:"groups,omitempty"`
	Following  []*Series   `protobuf:"bytes,9,rep,name=following" json:"following,omitempty"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}

func (m *Person) GetAttending() []*Activity {
	if m != nil {
		return m.Attending
	}
	return nil
}

func (m *Person) GetSpeakingAt() []*Activity {
	if m != nil {
		return m.SpeakingAt
	}
	return nil
}

func (m *Person) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Person) GetFollowing() []*Series {
	if m != nil {
		return m.Following
	}
	return nil
}

type Sponsor struct {
	Id                int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name              string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	MarketingContacts []*Person      `protobuf:"bytes,3,rep,name=marketingContacts" json:"marketingContacts,omitempty"`
	TechnicalContacts []*Person      `protobuf:"bytes,4,rep,name=technicalContacts" json:"technicalContacts,omitempty"`
	Sponsorships      []*Sponsorship `protobuf:"bytes,5,rep,name=sponsorships" json:"sponsorships,omitempty"`
}

func (m *Sponsor) Reset()         { *m = Sponsor{} }
func (m *Sponsor) String() string { return proto.CompactTextString(m) }
func (*Sponsor) ProtoMessage()    {}

func (m *Sponsor) GetMarketingContacts() []*Person {
	if m != nil {
		return m.MarketingContacts
	}
	return nil
}

func (m *Sponsor) GetTechnicalContacts() []*Person {
	if m != nil {
		return m.TechnicalContacts
	}
	return nil
}

func (m *Sponsor) GetSponsorships() []*Sponsorship {
	if m != nil {
		return m.Sponsorships
	}
	return nil
}

type Sponsorship struct {
	Id      int64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Event   *Event            `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	Sponsor *Sponsor          `protobuf:"bytes,3,opt,name=sponsor" json:"sponsor,omitempty"`
	Level   Sponsorship_Level `protobuf:"varint,4,opt,name=level,enum=Sponsorship_Level" json:"level,omitempty"`
}

func (m *Sponsorship) Reset()         { *m = Sponsorship{} }
func (m *Sponsorship) String() string { return proto.CompactTextString(m) }
func (*Sponsorship) ProtoMessage()    {}

func (m *Sponsorship) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Sponsorship) GetSponsor() *Sponsor {
	if m != nil {
		return m.Sponsor
	}
	return nil
}

type Vendor struct {
	Id          int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Contacts    []*Person  `protobuf:"bytes,3,rep,name=contacts" json:"contacts,omitempty"`
	Appearances []*Vending `protobuf:"bytes,4,rep,name=appearances" json:"appearances,omitempty"`
}

func (m *Vendor) Reset()         { *m = Vendor{} }
func (m *Vendor) String() string { return proto.CompactTextString(m) }
func (*Vendor) ProtoMessage()    {}

func (m *Vendor) GetContacts() []*Person {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Vendor) GetAppearances() []*Vending {
	if m != nil {
		return m.Appearances
	}
	return nil
}

type Vending struct {
	Id       int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Event    *Event                     `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	Vendor   *Vendor                    `protobuf:"bytes,3,opt,name=vendor" json:"vendor,omitempty"`
	Location *Location                  `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Begins   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=begins" json:"begins,omitempty"`
	Ends     *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=ends" json:"ends,omitempty"`
}

func (m *Vending) Reset()         { *m = Vending{} }
func (m *Vending) String() string { return proto.CompactTextString(m) }
func (*Vending) ProtoMessage()    {}

func (m *Vending) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Vending) GetVendor() *Vendor {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *Vending) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Vending) GetBegins() *google_protobuf.Timestamp {
	if m != nil {
		return m.Begins
	}
	return nil
}

func (m *Vending) GetEnds() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ends
	}
	return nil
}

func init() {
	proto.RegisterEnum("Activity_Type", Activity_Type_name, Activity_Type_value)
	proto.RegisterEnum("Sponsorship_Level", Sponsorship_Level_name, Sponsorship_Level_value)
}
